version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: testassignment-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: test_assignment
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: