spring:
  application:
    name: test-assignment

  datasource:
    url: jdbc:postgresql://localhost:5432/test_assignment
    username: test_user
    password: test_password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
